### ISSUE TITLE
Crash when trying to send small amount (dust)

### ISSUE THREAD

**Issue by volbil** [y-chan/atomicswap-qt#21]
Once I tried to participate in swap, this happened.

```Traceback (most recent call last):
  File "/Users/vova/Desktop/Work/PERSONAL/atomicswap-qt/atomicswap/qt/atomicswap_window.py", line 535, in next_page
    self.send_coind)
  File "~/atomicswap-qt/atomicswap/participate.py", line 39, in participate
    b = buildContract(contract, coind)
  File "~/atomicswap-qt/atomicswap/contract.py", line 96, in buildContract
    coind, fee_per_kb, min_fee_per_kb)
  File "~/atomicswap-qt/atomicswap/contract.py", line 136, in buildRefund
    raise BuildContractError(f"refund output value of {value} is dust")
atomicswap.contract.BuildContractError: refund output value of -5051 is dust
Abort trap: 6
```

Dust itself isn't an issue, but app probably should handle this error message.

**Comment by y-chan** [comment]
I temporary fixed it.
https://github.com/y-chan/atomicswap-qt/commit/67a1ed0c33c1a2dd4f4aa4f5c3805275312b4498

**Comment by volbil** [comment]
Thanks :)
